# simulation_settings:
MOTOR_MAX_FORCE = 1.5  # Adjust the maximum force according to your requirements
MOTOR_MAX_VELOCITY = 1.6 # 5.16 - speed of the motors
LINEAR_FRICTION = 10  # Set the linear friction coefficient (adjust as needed)
ANGULAR_FRICTION = 0.04  # Set the angular friction coefficient (adjust as needed)
NUM_PROCESSES = 12
PRINT_SIMULATION = False

# training_settings:
POPULATION_SIZE = 100
NUM_OF_POPULATIONS = 5
MAX_GENERATIONS = 10000
STUCK_GENERATIONS_TO_SUICIDE = 200
STUCK_GENERATIONS_TO_MOVE_ON = 500
NUM_REPLACED = 10

MUTATION_RATE = 0.05
STARTING_MUTATION_RANGE = 2.1
MUTATION_RANGE_DOWNWARDS_MULTIPLIER = 0.95
STUCK_GENERATIONS_TO_DECREASE = 16
MUTATION_RANGE_UPWARDS_MULTIPLIER = 1.03
STUCK_GENERATIONS_TO_INCREASE = 155

SAVE_GENERATION = True
PRINT_PROGRESS = True
USE_EXISTING_NETWORK = False
INITIAL_FILE_PATH = "networks\\walk_fine1.5.pkl"
